In [2]:
import numpy as np

In [3]:
arr1 = np.array([])
arr1

array([], dtype=float64)

In [10]:
mylist = [1,2.2,3,4,5]
mylist

[1, 2.2, 3, 4, 5]

In [11]:
a = np.array(mylist)
a


array([1. , 2.2, 3. , 4. , 5. ])

In [8]:
type(a)

numpy.ndarray

In [12]:
#no of dimesions in the array
a.ndim

1

In [13]:
a.size

5

In [14]:
a.shape

(5,)

Arrays can be n dimensions


In [31]:
my_nums = [[1,2,3,4.6],[5,6,7,8],[9,10,11,12]]
my_nums

[[1, 2, 3, 4.6], [5, 6, 7, 8], [9, 10, 11, 12]]

In [32]:
b = np.array(my_nums)
b

array([[ 1. ,  2. ,  3. ,  4.6],
       [ 5. ,  6. ,  7. ,  8. ],
       [ 9. , 10. , 11. , 12. ]])

In [33]:
print("The dimension of array", b.ndim)

The dimension of array 2


In [34]:
b.size

12

In [35]:
b.shape

(3, 4)

In [37]:
b.dtype

dtype('float64')

In [49]:
arr2= np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
arr2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [50]:
arr2.shape

(2, 2, 3)

In [ ]:
arr2[0][0][1]

np.int64(2)

: 

In [54]:
arr2[1][1][2]

np.int64(12)

In [4]:
#create an eye from a zero arrays
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
big_one = np.ones((3,4))
print(big_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
big_one * 3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

Random num generator

In [7]:
arr = np.random.rand()
arr

0.305295539824295

In [8]:
np.random.rand(10)

array([0.62612721, 0.63757888, 0.50067125, 0.42234236, 0.53231123,
       0.68789343, 0.58194571, 0.57679645, 0.57633944, 0.2905034 ])

In [3]:
np.random.rand(1,4,2)

array([[[0.17404733, 0.79578598],
        [0.8001465 , 0.66063961],
        [0.73719126, 0.80969062],
        [0.50776079, 0.53538487]]])

In [4]:
np.random.randint(10,100,5)

array([64, 68, 81, 44, 14], dtype=int32)

In [7]:
np.random.randint(29,30)

29